version: '{build}'
platform:
  - x64
image:
  - Visual Studio 2019
  - Ubuntu1804
install:
  - cmd: cd c:\tools\vcpkg
  - cmd: git pull
  - cmd: bootstrap-vcpkg.bat
  - cmd: vcpkg install freetype glfw3 --triplet x64-windows-static
  - cmd: vcpkg integrate install
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
build_script:
  - cmd: msbuild .\update\build\win32\update.vcxproj
  - cmd: msbuild .\profiler\build\win32\Tracy.vcxproj
  - cmd: msbuild .\capture\build\win32\capture.vcxproj
  - sh: sudo apt-get update && sudo apt-get -y install libglfw3-dev libgtk2.0-dev
  - sh: make -C update/build/unix debug release
  - sh: make -C profiler/build/unix debug release
  - sh: make -C capture/build/unix debug release
  - sh: make -C test
  - sh: make -C test clean
  - sh: make -C test TRACYFLAGS=-DTRACY_ON_DEMAND
test: off
